easy_admin:
  site_name: 'Backend Bolsa'
  user:
    name_property_path: 'username'
    display_name: true
    display_avatar: false
  entities:
    User:
      class: App\Entity\User
      controller: App\Controller\Admin\UserController
      form:
        fields:
          - { property: 'Name', type: 'text' }
          - { property: 'Username', type: 'text' }
          - { property: 'Email', type: 'email' }
          - { property: 'Password', type: 'password' }
          - { property: 'Roles', type: 'text' }
    Job:
      class: App\Entity\Job
